# Generated by Django 5.0.7 on 2024-10-04 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliations', '0002_affiliation_is_active'),
        ('companies', '0003_alter_company_options_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliations', models.ManyToManyField(related_name='units', to='affiliations.affiliation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company')),
            ],
        ),
    ]
