# Generated by Django 5.0.7 on 2024-10-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_unit_delete_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], max_length=50),
        ),
    ]
