# Generated by Django 5.1.2 on 2024-10-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_unit_price_unit_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], max_length=50),
        ),
    ]
