# Generated by Django 5.1.2 on 2024-10-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0006_alter_broker_email'),
        ('units', '0005_alter_unit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='location',
        ),
        migrations.AddField(
            model_name='unit',
            name='balcony',
            field=models.CharField(blank=True, choices=[('has_balcony', 'Has Balcony'), ('no_balcony', 'No Balcony')], max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='commission',
            field=models.DecimalField(decimal_places=2, help_text='Commission earned when the unit is sold', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='floor',
            field=models.PositiveIntegerField(default=1, help_text='Floor number'),
        ),
        migrations.AddField(
            model_name='unit',
            name='sold_by_broker',
            field=models.ForeignKey(blank=True, help_text='Broker who marked this unit as sold', null=True, on_delete=django.db.models.deletion.SET_NULL, to='brokers.broker'),
        ),
    ]
