# Generated by Django 5.1.2 on 2024-10-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_remove_unit_location_unit_balcony_unit_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='sold_by_broker',
        ),
    ]
