# Generated by Django 5.1.2 on 2024-11-06 05:14

import units.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_remove_unit_affiliations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='title',
            new_name='unit_title',
        ),
        migrations.AddField(
            model_name='unit',
            name='bathroom',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='bedroom',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=units.models.logo_upload_path),
        ),
    ]
