# Generated by Django 5.1.2 on 2024-11-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_rename_title_unit_unit_title_unit_bathroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], max_length=50),
        ),
    ]
