# Generated by Django 5.1.2 on 2024-11-12 03:27

import django.db.models.deletion
import units.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_alter_unit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=units.models.logo_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='units.unit')),
            ],
            options={
                'verbose_name': 'Unit Image',
                'verbose_name_plural': 'Unit Images',
            },
        ),
    ]
