# Generated by Django 5.1.2 on 2024-11-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0011_unitimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitImage',
        ),
    ]
