# Generated by Django 5.1.2 on 2024-11-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0013_alter_unit_balcony_alter_unit_status'),
        ('units', '0013_remove_unit_picture_unitimage'),
    ]

    operations = [
    ]
