# Generated by Django 5.1.2 on 2024-11-28 18:24

import django.core.validators
import django.db.models.deletion
import units.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_other_charges_site_reservation_fee_and_more'),
        ('units', '0014_merge_20241115_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bedroom', models.PositiveIntegerField(default=1)),
                ('bathroom', models.PositiveIntegerField(default=1)),
                ('floor_area', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('lot_area', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('view', models.CharField(choices=[('south', 'South'), ('north', 'North'), ('east', 'East'), ('west', 'West')], max_length=10)),
                ('balcony', models.CharField(choices=[('has balcony', 'Has Balcony'), ('no balcony', 'No Balcony')], max_length=20)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the template')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/unit_templates/')),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='quantity',
        ),
        migrations.AddField(
            model_name='unit',
            name='other_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='reservation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='spot_discount_flat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat spot discount amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='spot_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Spot discount percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(blank=True, help_text='Auto-generated Unit Number (e.g., 21001)', max_length=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unitimage',
            name='image_type',
            field=models.CharField(choices=[('unit', 'Unit'), ('unit_template', 'Unit Template')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='sites.floor'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending reservation', 'Pending Reservation'), ('reserved', 'Reserved')], max_length=50),
        ),
        migrations.AlterField(
            model_name='unitimage',
            name='image',
            field=models.ImageField(upload_to=units.models.logo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), units.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='unitimage',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='units.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='units.unittemplate'),
        ),
        migrations.AddField(
            model_name='unitimage',
            name='unit_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='units.unittemplate'),
        ),
    ]
