# Generated by Django 5.0.7 on 2024-11-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0014_merge_20241115_0934'),
        ('units', '0014_merge_20241115_2148'),
    ]

    operations = [
    ]
