# Generated by Django 5.1.2 on 2024-11-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0017_unit_unit_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittemplate',
            name='image',
        ),
    ]
