# Generated by Django 5.1.2 on 2024-11-29 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_other_charges_site_reservation_fee_and_more'),
        ('units', '0019_remove_unit_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='sites.floor'),
            preserve_default=False,
        ),
    ]
