# Generated by Django 5.1.2 on 2024-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0023_unittemplate_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Pending Reservation', 'Pending Reservation'), ('Reserved', 'Reserved')], max_length=50),
        ),
    ]
