# Generated by Django 5.1.2 on 2024-12-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0024_unittype_unit_unit_type_unittemplate_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitimage',
            name='primary',
            field=models.BooleanField(default=False, help_text='Indicates if this image is the primary image for the template'),
        ),
        migrations.AddField(
            model_name='unittemplate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unittemplate',
            name='primary_image',
            field=models.ForeignKey(blank=True, help_text='Primary image for the template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_templates', to='units.unitimage'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
