# Generated by Django 5.1.2 on 2024-12-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_logo_alter_company_name'),
        ('sites', '0013_site_maximum_months'),
        ('units', '0025_unitimage_primary_unittemplate_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='balcony',
            field=models.CharField(blank=True, choices=[('has balcony', 'Has Balcony'), ('no balcony', 'No Balcony')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='view',
            field=models.CharField(blank=True, choices=[('south', 'South'), ('north', 'North'), ('east', 'East'), ('west', 'West')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['site', 'status'], name='units_unit_site_id_b592df_idx'),
        ),
    ]
