# Generated by Django 5.1.2 on 2024-12-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0024_alter_unit_status'),
        ('units', '0025_unitimage_primary_unittemplate_last_updated_and_more'),
    ]

    operations = [
    ]
