# Generated by Django 5.1.2 on 2024-12-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0026_alter_unit_balcony_alter_unit_view_and_more'),
        ('units', '0026_merge_20241205_2204'),
    ]

    operations = [
    ]
