# Generated by Django 5.0.7 on 2024-12-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0026_merge_20241205_2204'),
        ('units', '0026_merge_20241205_2259'),
    ]

    operations = [
    ]
