# Generated by Django 5.0.7 on 2024-12-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0027_merge_20241205_2305'),
        ('units', '0027_merge_20241207_1310'),
    ]

    operations = [
    ]
