# Generated by Django 5.0.7 on 2024-12-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0028_merge_20241207_1344'),
        ('units', '0028_merge_20241207_1436'),
    ]

    operations = [
    ]
