# Generated by Django 5.1.2 on 2024-12-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0028_merge_20241207_1436'),
        ('units', '0028_merge_20241207_1551'),
    ]

    operations = [
    ]
