# Generated by Django 5.1.2 on 2024-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0028_merge_20241207_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitimage',
            name='primary',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if this image is the primary image for the template', null=True),
        ),
    ]
