# Generated by Django 5.1.2 on 2024-12-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0029_alter_unitimage_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittemplate',
            name='balcony',
            field=models.CharField(blank=True, choices=[('has balcony', 'Has Balcony'), ('no balcony', 'No Balcony')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unittemplate',
            name='view',
            field=models.CharField(blank=True, choices=[('south', 'South'), ('north', 'North'), ('east', 'East'), ('west', 'West')], max_length=10, null=True),
        ),
    ]
