# Generated by Django 5.1.2 on 2024-12-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0030_alter_unittemplate_balcony_alter_unittemplate_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittemplate',
            name='relative_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
