# Generated by Django 5.1.2 on 2024-12-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0031_unittemplate_relative_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittemplate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
