# Generated by Django 5.1.2 on 2024-12-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_logo_alter_company_name'),
        ('units', '0032_unittemplate_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittype',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company'),
            preserve_default=False,
        ),
    ]
