# Generated by Django 5.1.2 on 2024-12-12 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_logo_alter_company_name'),
        ('units', '0033_unittype_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='floor',
            new_name='section',
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(blank=True, help_text='Auto-generated Unit Number (e.g., 21001)', max_length=20),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company'),
        ),
    ]
