# Generated by Django 5.1.2 on 2024-12-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_logo_alter_company_name'),
        ('units', '0035_alter_unit_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='unittemplate',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_unit_template_per_company'),
        ),
    ]
