# Generated by Django 5.1.2 on 2024-12-15 00:32

from django.db import migrations

def create_default_unit_types(apps, schema_editor):
    UnitType = apps.get_model('units', 'UnitType')
    default_unit_types = [
        'Studio', 'Studio Deluxe', '1 Bedroom', '2 Bedroom', '3 Bedroom', 'Penthouse', 'Loft'
    ]
    
    for unit_type in default_unit_types:
        UnitType.objects.get_or_create(
            name=unit_type, 
            defaults={'is_custom': False}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('units', '0036_alter_unittemplate_name_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_unit_types),
    ]