# Generated by Django 5.1.2 on 2024-12-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0037_alter_unit_unit_type_alter_unittemplate_company_and_more'),
        ('units', '0037_populate_default_unit_types'),
    ]

    operations = [
    ]
