# Generated by Django 5.1.2 on 2024-12-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0039_update_default_unit_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittemplate',
            name='bathroom',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='unittemplate',
            name='bedroom',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='unittemplate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
