# Generated by Django 5.1.1 on 2024-09-20 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('condominium', 'Condominium'), ('commercial', 'Commercial'), ('other', 'Other')], default=('house', 'House'), max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_listed', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=100)),
                ('sqm', models.IntegerField()),
                ('bedroom', models.IntegerField(default=1)),
                ('bathroom', models.IntegerField(default=1)),
                ('garage', models.IntegerField(default=0)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('count_report', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Properties',
        ),
    ]
