# Generated by Django 5.1.1 on 2024-09-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='highlighted_description',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
