# Generated by Django 5.0.7 on 2024-10-02 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing Process'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('affiliated_link', models.URLField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brokers.broker')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company')),
            ],
        ),
    ]
