# Generated by Django 5.0.7 on 2024-10-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_name_customer_first_name_and_more'),
        ('units', '0004_unit_price_unit_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='description',
        ),
        migrations.AddField(
            model_name='customer',
            name='unit',
            field=models.ManyToManyField(blank=True, related_name='customers', to='units.unit'),
        ),
    ]
