# Generated by Django 5.0.7 on 2024-10-31 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customer_date_sold_remove_customer_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
    ]
