# Generated by Django 5.1.2 on 2024-11-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_customer_affiliated_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(default='CUST-001', max_length=10, unique=True),
        ),
    ]
