# Generated by Django 5.1.2 on 2024-11-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customer_customer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_code',
        ),
    ]
