# Generated by Django 5.1.2 on 2024-12-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
