# Generated by Django 5.1.2 on 2024-12-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customer_customer_code_and_more'),
        ('customers', '0013_remove_customer_customer_code'),
    ]

    operations = [
    ]
