# Generated by Django 5.0.7 on 2024-10-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_options_alter_company_logo'),
        ('units', '0004_unit_price_unit_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='units.unit')),
            ],
        ),
    ]
