# Generated by Django 5.1.2 on 2024-11-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_milestone_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='commission_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='sales_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='type',
            field=models.CharField(choices=[('sales', 'Sales'), ('commission', 'Commission')], default='sales', max_length=10),
        ),
    ]
