# Generated by Django 5.0.7 on 2024-10-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0002_affiliation_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='is_active',
        ),
    ]
