# Generated by Django 5.1.2 on 2024-11-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'under_review'), ('sold', 'Sold')], default='pending', max_length=20),
        ),
    ]
