# Generated by Django 5.0.7 on 2024-11-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under review', 'Under Review'), ('sold', 'Sold')], default='pending', max_length=20),
        ),
    ]
