# Generated by Django 5.1.2 on 2024-11-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending reservation', 'Pending Reservation'), ('Reserved', 'Reserved')], default='pending', max_length=20),
        ),
    ]
