# Generated by Django 5.1.2 on 2024-11-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_status'),
        ('sales', '0006_sale_payment_method_sale_payment_reference_and_more'),
    ]

    operations = [
    ]
