# Generated by Django 5.0.7 on 2024-11-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_payment_method_sale_payment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending reservation', 'Pending Reservation'), ('reserved', 'Reserved'), ('pending sold', 'Pending Sold'), ('sold', 'Sold')], default='pending_reservation', max_length=20),
        ),
    ]
