# Generated by Django 5.1.2 on 2024-11-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_merge_20241115_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending reservation', 'Pending Reservation'), ('reserved', 'Reserved'), ('pending sold', 'Pending Sold'), ('sold', 'Sold')], default='pending_reservation', max_length=20),
        ),
    ]
