# Generated by Django 5.0.7 on 2024-11-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_merge_20241115_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending_reservation', 'Pending Reservation'), ('reserved', 'Reserved'), ('pending_sold', 'Pending Sold'), ('sold', 'Sold')], default='pending_reservation', max_length=20),
        ),
    ]
