# Generated by Django 5.1.2 on 2024-11-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Pending Reservation', 'Pending Reservation'), ('Reserved', 'Reserved'), ('Pending Sold', 'Pending Sold'), ('Sold', 'Sold')], default='pending_reservation', max_length=20),
        ),
    ]
