# Generated by Django 5.1.2 on 2024-12-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]