# Generated by Django 5.1.2 on 2024-12-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Pending Reservation', 'Pending Reservation'), ('Reserved', 'Reserved'), ('Pending Sold', 'Pending Sold'), ('Sold', 'Sold')], default='Pending Reservation', max_length=20),
        ),
    ]
