# Generated by Django 5.1.2 on 2024-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_sale_date_sold_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The commission earned from this sale (based on the unit's commission)", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
