# Generated by Django 5.1.2 on 2024-12-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_is_archived'),
        ('sales', '0011_sale_commission_alter_sale_date_sold'),
    ]

    operations = [
    ]
