# Generated by Django 5.1.2 on 2024-12-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_merge_20241204_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The commission earned from this sale (based on the unit's commission)", max_digits=20, null=True),
        ),
    ]
