# Generated by Django 5.1.2 on 2024-11-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesdetails', '0001_initial'),
        ('sites', '0006_remove_site_affiliations'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdetails',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
