# Generated by Django 5.1.2 on 2024-11-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesdetails', '0002_salesdetails_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdetails',
            name='reservation_agreement',
            field=models.FileField(blank=True, null=True, upload_to='reservation_agreements/'),
        ),
    ]
