# Generated by Django 5.0.7 on 2024-10-04 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0003_remove_affiliation_is_active'),
        ('companies', '0003_alter_company_options_alter_company_logo'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('affiliations', models.ManyToManyField(related_name='sites', to='affiliations.affiliation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
