# Generated by Django 5.0.7 on 2024-10-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_delete_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('preselling', 'Preselling'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('sold_out', 'Sold Out')], default='preselling', max_length=20),
        ),
    ]
