# Generated by Django 5.1.2 on 2024-10-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_site_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='site_pictures/'),
        ),
    ]
