# Generated by Django 5.1.2 on 2024-11-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_site_created_at_alter_site_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='affiliations',
        ),
    ]
