# Generated by Django 5.1.2 on 2024-11-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_remove_site_affiliations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, default='No description provided'),
        ),
    ]
