# Generated by Django 5.1.2 on 2024-11-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
