# Generated by Django 5.1.2 on 2024-12-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_other_charges_site_reservation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='commission',
            field=models.DecimalField(decimal_places=2, help_text='Commission earned when the unit is sold', max_digits=10, null=True),
        ),
    ]
