# Generated by Django 5.1.2 on 2024-12-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_site_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='maximum_months',
            field=models.PositiveIntegerField(default=360, help_text='Maximum months for payment term (e.g., 360 for 30 years)'),
        ),
    ]
