# Generated by Django 5.1.2 on 2024-12-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_site_maximum_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='maximum_months',
            field=models.PositiveIntegerField(default=60, help_text='Maximum months for payment term (e.g., 60 months for 5 years max)'),
        ),
    ]
