# Generated by Django 5.1.2 on 2024-12-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_rename_floor_number_floor_number_floor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='site',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sites.site')),
            ],
        ),
    ]
