# Generated by Django 5.1.2 on 2024-12-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_remove_floor_site_section'),
        ('units', '0035_alter_unit_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
