# Generated by Django 5.1.2 on 2024-12-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_alter_site_maximum_months'),
        ('sites', '0016_delete_floor'),
    ]

    operations = [
    ]
