# Generated by Django 5.1.2 on 2024-12-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_merge_20241212_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='numbering_type',
            field=models.CharField(choices=[('numeric', '1, 2, 3'), ('alphabetic', 'A, B, C')], default='numeric', max_length=10),
        ),
        migrations.AddField(
            model_name='site',
            name='section_label',
            field=models.CharField(choices=[('section', 'Section'), ('floor', 'Floor'), ('block', 'Block'), ('level', 'Level')], default='floor', max_length=10),
        ),
    ]
