# Generated by Django 5.1.2 on 2024-12-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_logo_alter_company_name'),
        ('sites', '0020_alter_site_other_charges_alter_site_reservation_fee_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_site_per_company'),
        ),
    ]
