# Generated by Django 5.1.2 on 2024-12-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0021_site_unique_site_per_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='relative_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
