# Generated by Django 5.1.2 on 2024-12-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0023_alter_site_relative_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='maximum_months',
            field=models.PositiveIntegerField(default=60, help_text='Maximum months for downpayment (e.g., 24 months for 2 years max)'),
        ),
    ]
