# Generated by Django 5.1.2 on 2024-11-14 15:18

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documenttype_document_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.document_file_upload_path),
        ),
    ]
