# Generated by Django 5.1.2 on 2024-11-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
