# Generated by Django 5.1.2 on 2024-11-29 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_documents_d_content_ba3031_idx_and_more'),
        ('sales', '0008_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.sale'),
            preserve_default=False,
        ),
    ]
