# Generated by Django 5.0.7 on 2024-10-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
