# Generated by Django 5.0.7 on 2024-10-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_developer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
