# Generated by Django 5.1.2 on 2024-10-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_remove_developer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
