# Generated by Django 5.1.2 on 2024-11-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0008_remove_developer_name_developer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='developer',
            name='contact_number',
        ),
        migrations.AlterField(
            model_name='developer',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
