# Generated by Django 5.1.2 on 2024-11-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0009_alter_developer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='contact_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
