# Generated by Django 5.1.2 on 2024-11-18 16:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('unit_title', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_plan', models.CharField(max_length=255)),
                ('spot_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('net_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reservation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_full_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spot_downpayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spread_downpayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payable_months', models.IntegerField()),
                ('payable_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_upon_turnover', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
