# Generated by Django 5.0.7 on 2024-10-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
