# Generated by Django 5.1.2 on 2024-10-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0005_remove_broker_description_remove_broker_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
