# Generated by Django 5.1.2 on 2024-10-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0006_alter_broker_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
