# Generated by Django 5.1.2 on 2024-11-06 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0009_remove_broker_name_broker_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='affiliations',
        ),
    ]
