# Generated by Django 5.1.2 on 2024-11-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0010_remove_broker_affiliations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
