# Generated by Django 5.1.2 on 2024-11-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0011_alter_broker_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='password',
            field=models.CharField(default='12345', max_length=128, null=True),
        ),
    ]
