# Generated by Django 5.1.2 on 2024-11-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0012_alter_broker_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
