# Generated by Django 5.1.2 on 2024-11-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0013_alter_broker_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
