# Generated by Django 5.1.2 on 2024-11-17 09:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0015_alter_broker_email_alter_broker_password'),
        ('companies', '0005_alter_company_logo_alter_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='broker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Enter a valid phone number (9 to 15 digits).')]),
        ),
    ]
