# Generated by Django 5.1.2 on 2024-11-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0017_broker_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
