# Generated by Django 5.1.2 on 2024-11-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0018_alter_broker_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='is_active',
        ),
    ]
