# Generated by Django 5.1.2 on 2024-12-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0019_remove_broker_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='relative_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
