# Generated by Django 5.1.2 on 2024-12-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0020_broker_relative_id'),
        ('companies', '0005_alter_company_logo_alter_company_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['company', 'relative_id'], name='brokers_bro_company_b01a5e_idx'),
        ),
    ]
