# Generated by Django 5.1.2 on 2024-12-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0021_broker_brokers_bro_company_b01a5e_idx'),
        ('companies', '0005_alter_company_logo_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='relative_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='broker',
            constraint=models.UniqueConstraint(fields=('company', 'relative_id'), name='unique_company_relative_id'),
        ),
    ]
